//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonRehberi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisiler
    {
        public int KisilerID { get; set; }
        public string KisiAdi { get; set; }
        public string KisiSoyadi { get; set; }
        public string Email { get; set; }
        public string Sirket { get; set; }
        public string TelNo { get; set; }
    }
}
